[package]
name = "dackky/fruit-magnet-simulator"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@^3.1.0"
Signal = "sleitnick/signal@^1.0.1"
Component = "sleitnick/component@^2.4.5"
Timer = "sleitnick/timer@1.1.2"
TableUtil = "sleitnick/table-util@1.2.1"
cardinal = "remnantsofsiren/cardinal@1.7.2"
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
ReactSpring = "chriscerie/react-spring@2.0.0"


[server-dependencies]
ProfileService = "brittonfischer/profileservice@^2.1.5"